PRINT "Circ orbit v0.1".
WAIT UNTIL SHIP:STATUS = "SUB_ORBITAL".
LOCK STEERING TO SHIP:PROGRADE.
PRINT "Suborbital flight".

WAIT UNTIL ETA:APOAPSIS < 15.
LOCK STEERING TO SHIP:PROGRADE.

LOCAL alt IS ORBIT:APOAPSIS.
LOCK THROTTLE TO 1.
STAGE.

UNTIL ORBIT:PERIAPSIS >= 71000 {
  LOCK STEERING TO SHIP:PROGRADE.
  WAIT 0.1.
}

UNLOCK THROTTLE.
PRINT "Orbit reached".
